# Generated by Django 4.1.7 on 2023-03-17 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=50)),
                ('celular', models.TextField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='FormasDePagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pagamento', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=50)),
                ('endereco', models.TextField(max_length=300, verbose_name='Endereço')),
                ('horario', models.TextField(max_length=50, verbose_name='Horário')),
                ('telefone', models.TextField(max_length=11)),
                ('website', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.TextField(max_length=50)),
                ('descricao', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField(max_length=50)),
                ('descricao', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Subservico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_cobranca', models.TextField(max_length=50)),
                ('descricao', models.TextField(max_length=50, verbose_name='Descrição')),
                ('valor', models.FloatField()),
                ('duracao', models.TimeField(verbose_name='Duração')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.servico')),
            ],
        ),
        migrations.AddField(
            model_name='servico',
            name='tipoServico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.tiposervico'),
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=50)),
                ('telefone', models.TextField(max_length=11)),
                ('resumo', models.TextField(max_length=500)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.loja')),
            ],
        ),
        migrations.CreateModel(
            name='Oferece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.profissional')),
                ('subservico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.subservico')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.cliente')),
                ('formaPagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.formasdepagamento')),
                ('oferece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.oferece')),
            ],
        ),
        migrations.CreateModel(
            name='Aceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formaDePagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.formasdepagamento')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.loja')),
            ],
        ),
    ]
