# Generated by Django 4.1.7 on 2023-03-17 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='oferece',
        ),
        migrations.RemoveField(
            model_name='oferece',
            name='subservico',
        ),
        migrations.AddField(
            model_name='agenda',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.profissional'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agenda',
            name='subservico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.subservico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oferece',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.servico'),
            preserve_default=False,
        ),
    ]
