# Generated by Django 4.1.7 on 2023-03-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_remove_agenda_oferece_remove_oferece_subservico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='email',
            field=models.TextField(default='salo@salo.co', max_length=50),
            preserve_default=False,
        ),
    ]
