# Generated by Django 4.2.1 on 2023-05-12 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_servico_fotoprincipal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='subservico',
        ),
        migrations.AddField(
            model_name='agenda',
            name='servico',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='agenda.servico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servico',
            name='duracao',
            field=models.TimeField(default=None, verbose_name='Duração'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servico',
            name='valor',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Subservico',
        ),
    ]
