# Generated by Django 4.2.1 on 2023-05-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_remove_agenda_subservico_agenda_servico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
