# Generated by Django 4.2.1 on 2023-05-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_alter_servico_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
