# Generated by Django 4.2.1 on 2023-05-12 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_alter_servico_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='profissional',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='agenda.profissional'),
        ),
    ]
