# Generated by Django 4.2.1 on 2023-05-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_remove_agenda_profissional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferece',
            name='profissional',
        ),
        migrations.RemoveField(
            model_name='oferece',
            name='servico',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='loja',
        ),
        migrations.AlterField(
            model_name='formasdepagamento',
            name='tipo_pagamento',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.DeleteModel(
            name='Aceita',
        ),
        migrations.DeleteModel(
            name='Loja',
        ),
        migrations.DeleteModel(
            name='Oferece',
        ),
        migrations.DeleteModel(
            name='Profissional',
        ),
    ]
